
# Introduction to Linear Algebra

## Vectors

The fundamental building blocks of linear algebra are **vectors**. Vectors are defined as 
quantities having both **direction** and **magnitude** (length), compared to scalar quantities that 
only have magnitude. In order to have direction and magnitude, vector quantities consist of two or 
more elements of data. The **dimensionality of a vector** is determined by the number of numerical 
elements in that vector.

Let’s take a look at examples of a scalar versus a vector. A car driving at a speed of 40mph is a 
scalar quantity. Describing the car driving 40mph to the east would represent a two-dimensional 
vector quantity since it has a magnitude in both the x and y directions.
<br>
$ 
\mathbf{v} = \begin{pmatrix}
        a \\
        b \\
        c
\end{pmatrix} 
$

The magnitude (or length) of a vector, ||v||, can be calculated with the following formula:
<br>
||v|| = $ \sqrt{\sum_{i=1}^n{v_i^2}} $

This approach is grounded in the **Pythagorean theorem**, especially in 2D and 3D space. For 
instance, in a 2D space, if you consider a vector $ (v_1, v_2) $ as forming a right-angled 
triangle with the axes, the magnitude represents the hypotenuse, and the Pythagorean theorem applies.
<br>
## Basic Vector operations

### Scalar multiplication

Any vector can be multiplied by a scalar, which results in every element of that vector being 
multiplied by that scalar individually.
<br>
$ k * \begin{pmatrix}
        a \\
        b \\
        c
\end{pmatrix} = \begin{pmatrix}
        k * a \\
        k * b \\
        k * c
\end{pmatrix} 
$

### Vector Addition and Subtraction

Vectors can be added and subtracted from each other when they are of the same dimension (same number 
of components). Doing so adds or subtracts corresponding elements, resulting in a new vector of the 
same dimension as the two being summed or subtracted. 
<br>
$ \begin{pmatrix}
        x_1 \\
        y_1 \\
        z_1
\end{pmatrix} + 2 * \begin{pmatrix}
        x_2 \\
        y_2 \\
        z_2
\end{pmatrix} - 3 * \begin{pmatrix}
        x_3 \\
        y_3 \\
        z_3
\end{pmatrix} = \begin{pmatrix}
        x_1 + 2x_2 - 3x_3 \\
        y_1 + 2y_2 - 3y_3 \\
        z_1 + 2z_2 - 3z_3
\end{pmatrix}
$
<br>
## Vector Dot Products (Scalar Product)

An important vector operation in linear algebra is the dot product. A dot product takes two equal 
dimension vectors and returns a single scalar value by summing the products of the vectors’ 
corresponding components. This can be written out as:
<br>
$ a \cdot b = \sum_{i=1}^n{a_i*b_i} $

The resulting scalar value represents how much one vector “goes into” the other vector. If two 
vectors are orthogonal (perpendicular), their dot product is equal to 0, as neither vector “goes 
into the other.”

The dot product can also be used to find the magnitude of a vector and the angle between two 
vectors. To find the magnitude, we can see that the magnitude of a vector is simply the square root 
of a vector’s dot product with itself.
<br>
||v|| = $ \sqrt{v \cdot v} $

To find the angle between two vectors, we rely on the dot product between the two vectors and use 
the following equation.
<br>
$ \theta = arccos \frac{a * b}{||a|| * ||b||} $

## Matrices

The shape of a matrix is said to be mxn, where there are m rows and n columns. When representing 
matrices as a variable, we denote the matrix with a capital letter and a particular matrix element 
as the matrix variable with an “m,n” determined by the element’s location.
<br>
$ A = \begin{pmatrix}
        a, b, c \\
        d, e, f \\
        g, h, i
\end{pmatrix}
$
<br>$ A_{1,2} = b $

## Matrix operations

We can again both multiply entire matrices by a scalar value, as well as add or subtract matrices 
with equal shapes.
<br>
$ 2 * \begin{pmatrix}
        a_1, b_1 \\
        a_2, b_2
\end{pmatrix} + 3 * \begin{pmatrix}
        c_1, d_1 \\
        c_2, d_2
\end{pmatrix} = \begin{pmatrix}
        2a_1 + 3c_1, 2b_1 + 3d_1 \\
        2a_2 + 3c_2, 2b_2 + 3d_2
\end{pmatrix} $

A new and important operation we can now perform is **matrix multiplication**. Matrix multiplication 
works by computing the dot product between each row of the first matrix and each column of the 
second matrix.

$ \begin{pmatrix}
        1, 2, 3 \\
        4, 5, 6
\end{pmatrix} * \begin{pmatrix}
        7, 8  \\
        9, 10 \\
        11, 12
\end{pmatrix} = \begin{pmatrix}
        (1, 2, 3) \cdot (7, 9, 11), (1, 2, 3) \cdot (8, 10, 12) \\
        (4, 5, 6) \cdot (7, 9, 11), (4, 5, 6) \cdot (8, 10, 12)
\end{pmatrix} = \begin{pmatrix}
        58, 64 \\
        139, 154
\end{pmatrix} $

## Special Matrices

### Identity Matrix

The identity matrix is a square matrix of elements equal to 0 except for the elements along the 
diagonal that are equal to 1. Any matrix multiplied by the identity matrix, either on the left or 
right side, will be equal to itself.
<br>
$ \begin{pmatrix}
        1, 0, 0 \\
        0, 1, 0 \\
        0, 0, 1
\end{pmatrix}$

### Transpose Matrix

The transpose of a matrix is computed by swapping the rows and columns of a matrix. The transpose 
operation is denoted by a superscript uppercase “T” $(A^T)$.
<br>
$ \begin{pmatrix}
        a, b, c \\
        d, e, f \\
        g, h, i
\end{pmatrix}^T = \begin{pmatrix}
        a, d, g \\
        b, e, h \\
        c, f, i
\end{pmatrix}$

### Permutation Matrix

A permutation matrix is a square matrix that allows us to flip rows and columns of a separate 
matrix. Similar to the identity matrix, a permutation matrix is made of elements equal to 0, except 
for one element in each row or column that is equal to 1. In order to flip rows in matrix A, we 
multiply a permutation matrix P on the left (PA). To flip columns, we multiply a permutation matrix 
P on the right (AP).

#### Row Swap (P * A)
<br>
$ PA = \begin{pmatrix}
        0, 1, 0 \\
        0, 0, 1 \\
        1, 0, 0
\end{pmatrix} * \begin{pmatrix}
        a, b, c \\
        d, e, f \\
        g, h, i
\end{pmatrix} = \begin{pmatrix}
        d, e, f \\
        g, h, i \\
        a, b, c
\end{pmatrix} $

#### Column Swap (A * P)
<br>
$ AP = \begin{pmatrix}
        a, b, c \\
        d, e, f \\
        g, h, i
\end{pmatrix} * \begin{pmatrix}
        0, 1, 0 \\
        0, 0, 1 \\
        1, 0, 0
\end{pmatrix} = \begin{pmatrix}
        c, a, b \\
        f, d, e \\
        i, h, i
\end{pmatrix} $

## Linear Systems in Matrix Form

An extremely useful application of matrices is for solving systems of linear equations. Consider the 
following system of equations in its algebraic form.

$ a_1x + b_1y + c_1z = d_1 $ <br>
$ a_2x + b_2y + c_2z = d_2 $ <br>
$ a_3x + b_3y + c_3z = d_3 $ <br>

This system of equations can be represented using vectors and their linear combination operations 
that we discussed in the previous exercise. We combine the coefficients of the same unknown 
variables, as well as the equation solutions, into vectors. These vectors are then scalar multiplied 
by their unknown variable and summed.

$ x * \begin{pmatrix}
        a_1 \\
        a_2 \\
        a_3
\end{pmatrix} + y * \begin{pmatrix}
        b_1 \\
        b_2 \\
        b_3
\end{pmatrix} + z * \begin{pmatrix}
        c_1 \\
        c_2 \\
        c_3
\end{pmatrix} = \begin{pmatrix}
        d_1 \\
        d_2 \\
        d_3
\end{pmatrix} $
<br>
$ \begin{pmatrix}
        a_1, b_1, c_1 \\
        a_2, b_2, c_2 \\
        a_3, b_3, c_3
\end{pmatrix} * \begin{pmatrix}
        x \\
        y \\
        z
\end{pmatrix} = \begin{pmatrix}
        d_1 \\
        d_2 \\
        d_3
\end{pmatrix} $

### Augmented Matrix

We can also write Ax = b in the following form:
<br>
$ Ax = b \to [A | b] $
<br>
$ \begin{pmatrix}
        a_1, b_1, c_1 \\
        a_2, b_2, c_2 \\
        a_3, b_3, c_3
\end{pmatrix} * \begin{pmatrix}
        x \\
        y \\
        z
\end{pmatrix} = \begin{pmatrix}
        d_1 \\
        d_2 \\
        d_3
\end{pmatrix} \to \begin{pmatrix}
        a_1, b_1, c_1 | d_1 \\
        a_2, b_2, c_2 | d_2 \\
        a_3, b_3, c_3 | d_3
\end{pmatrix} $

## Gauss-Jordan Elimination

To solve for the system, we want to put our augmented matrix into a **row echelon form** 
where all elements below the diagonal are equal to zero. This looks like the following:
<br>
$ \begin{pmatrix}
        a_1, b_1, c_1 | d_1 \\
        a_2, b_2, c_2 | d_2 \\
        a_3, b_3, c_3 | d_3
\end{pmatrix} \to \begin{pmatrix}
        1, b'_1, c'_1 | d'_1 \\
        0, 1, c'_2 | d'_2 \\
        0, 0, 1 | d'_3
\end{pmatrix} $

Note that the values with apostrophes in the row echelon form matrix mean that they have been 
changed in the process of updating the matrix. Once in this form we can rewrite our original 
equation as:
<br>
$ x + b'_1y + c'_1z = d'_1 $ <br>
$ y + c'_2z = d'_2 $ <br>
$ z = d'_3 $

To get to row echelon form we swap rows and/or add or subtract rows against other rows. A typical 
strategy is to add or subtract row 1 against all rows below in order to make all elements in column 
1 equal to 0 under the diagonal. Once this is achieved, we can do the same with row 2 and all rows 
below to make all elements below the diagonal in column 2 equal to 0.

Once all elements below the diagonal are equal to 0, we can simply solve for the variable values, 
starting at the bottom of the matrix and working our way up.

## Inverse Matrices

The inverse of a matrix, A-1, is one where the following equation is true:
<br>
$ A * A^{-1} = A^{-1} * A = 1 $

The inverse matrix is useful in many contexts, one of which includes solving equations with 
matrices. Imagine we have the following equation:
<br>
$ x * A = B * C $ <br>
$ x * A * A^{-1} = B * C * A^{-1} $

An important consideration to keep in mind is that not all matrices have inverses. Those matrices 
that do not have an inverse are referred to as **singular matrices**.

To find the inverse matrix, we can again use Gauss-Jordan elimination. Knowing that AA-1 = I, we can 
create the augmented matrix [ A | I ], where we attempt to perform row operations such that [ A | I 
] -> [ I | A-1 ].

## Using NumPy Arrays

### Combining Existing Arrays to Create a Matrix

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

A = np.row_stack((a, b, c))
print(A)

u = np.array([1, 4, 7])
v = np.array([2, 5, 8])
w = np.array([3, 6, 9])

U = np.column_stack((u, v, w))
print(U)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Get Shape and Elements of a Matrix

In [11]:
import numpy as np

A = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])
print(A.shape)

# Indexing using commas
print(A[1,2])

X = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Get entire third column
print(X[:,2])

# Get the last two elements of the second column
print(X[-2:,1])

# Get the entire last row
print(X[-1:,:])

# Get the middle elements
print(X[1:3,1:3])

(2, 4)
7
[ 3  7 11 15]
[10 14]
[[13 14 15 16]]
[[ 6  7]
 [10 11]]


### Using Numpy for Linear Algebra Operation

In [20]:
import numpy as np

# Multiply matrix with scalar
A = np.array([
    [2, 4],
    [6, 8]
])
print(10 * A)

# Add Matrices
B = [
    [9, 7],
    [5, 3]
]
print(A + B)

# Subtract Matrices
print(B - A)

# Calculate dot-product
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
print(np.dot(a, b))

# Matrix multiplication
print(np.matmul(A, B))

[[20 40]
 [60 80]]
[[11 11]
 [11 11]]
[[ 7  3]
 [-1 -5]]
70
[[38 26]
 [94 66]]
[[18 28]
 [30 24]]


### Special Matrices

In [25]:
import numpy as np

# Create a 4x4 Identity Matrix
I = np.eye(4, 4)
print(I)

# Create a Vector containing only zeros
a = np.zeros(4)
print(a)

# Crate a Matrix containing only zeros
A = np.zeros((4,4))
print(A)

# Create the transpose of a Matrix
B = np.array([[1,2], [3,4], [5,6]])
print(B.T)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 3 5]
 [2 4 6]]


### Additional Linear Algebra Operations

In [32]:
import numpy as np

# Determine the length (magnitude) of a Vector
a = np.array([2, -4, 1])
print('Magnitude:', np.linalg.norm(a))

# Find the Inverse of a Matrix
A = np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

# Solve linear equation
#  x + 4y -  z = -1
# -x - 3y + 2z =  2
# 2x -  y - 2z = -2
B = np.array([[1, 4, -1], [-1, -3, 2], [2, -1, -2]])
b = np.array([-1, 2, -2])
x, y, z = np.linalg.solve(B, b)
print('x =', x, 'y =', y, 'z =', z)

Magnitude: 4.58257569495584
[[-2.   1. ]
 [ 1.5 -0.5]]
x = 0.0 y = 0.0 z = 1.0
-0.3333333333333333 -0.6666666666666666 0.6666666666666666
